### ISSUE TITLE
Properties population 

### ISSUE THREAD

**Issue by Star-Cat13** [lukaprelic/TheABCsGenerator#1]
I had been using the openseaupload.py to get my NFT's uploaded successfully for about a month now. I'm not sure if it's something Opensea changed or if the script can be updated but I cannot get the properties window to open anymore. From this section:

`        propertiesPlusButton = driver.find_element_by_xpath(
            '//*[@id="__next"]/div[1]/main/div/div/section/div/form/section/div[1]/div/div[2]/button')
        propertiesPlusButton.click()
        print('starting properties population')
        time.sleep(1.6)`

Edit: I found it was an error with my xpath.
Thanks

**Comment by AnhNPT** [comment]
Can you help me setup this script on my pc?
I need to change something in the script like select collection, etc but i do not learn python and not good at coding
